from __future__ import annotations

from typing import Any


_DESKTOP_BOUND_HIDDEN_TOOLS = frozenset(
    {
        "open_layout_session",
        "close_layout_session",
        "list_layout_paths",
        "preview_parameterize_path_width",
        "apply_parameterize_path_width",
        "list_live_aedt_sessions",
        "launch_live_aedt_session",
        "create_live_hfss_design",
        "start_live_hfss_analysis",
    }
)


def capability_catalog_v2(*, desktop_bound: bool = False) -> dict[str, Any]:
    capabilities = [
        _cap("aedt.sessions.list", "read_only", ["live"], ["list_live_aedt_sessions"]),
        _cap(
            "aedt.sessions.launch",
            "process_start",
            ["live"],
            ["launch_live_aedt_session"],
            side_effects=["starts_assistant_owned_aedt_process"],
        ),
        _cap("aedt.sessions.attach", "read_only", ["live"], ["attach_live_aedt_session"]),
        _cap(
            "aedt.approvals.wait",
            "read_only",
            ["live"],
            ["wait_for_live_approval"],
            postconditions=["token_returned_only_after_external_user_approval"],
        ),
        _cap(
            "aedt.sessions.release",
            "read_only",
            ["live"],
            ["release_live_aedt_session"],
            postconditions=["aedt_process_remains_running", "projects_remain_open"],
        ),
        _cap("aedt.projects.info", "read_only", ["live"], ["get_live_aedt_project_info"]),
        _cap(
            "aedt.projects.save",
            "persistent_write",
            ["live"],
            ["preview_live_project_save", "apply_live_project_save"],
            approval="external_host_token",
            postconditions=["preview_digest_unchanged", "project_saved"],
        ),
        _cap(
            "hfss.design.create",
            "reversible_edit",
            ["live"],
            ["create_live_hfss_design"],
            side_effects=["project_becomes_dirty"],
        ),
        _cap(
            "hfss.design.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_design_inventory"],
        ),
        _cap(
            "aedt.setups.inventory",
            "read_only",
            ["live"],
            ["get_live_aedt_setup_inventory"],
            postconditions=[
                "design_unchanged",
                "setup_and_sweep_names_returned",
                "aedt_port_order_returned",
            ],
        ),
        _cap(
            "aedt.solutions.inventory",
            "read_only",
            ["live"],
            ["get_live_aedt_solution_inventory"],
            postconditions=[
                "design_unchanged",
                "solved_setup_and_sweep_evidence_returned",
                "bounded_results_directory_snapshot_returned",
            ],
            products=["hfss", "layout"],
        ),
        _cap(
            "hfss.geometry.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_geometry_inventory"],
            postconditions=["design_unchanged", "face_selector_digest_returned"],
        ),
        _cap(
            "hfss.material.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_material_inventory"],
            postconditions=[
                "design_unchanged",
                "bounded_project_material_catalog_returned",
                "material_definition_digests_returned",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.material.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_material_create",
                "apply_live_hfss_material_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "new_project_material_definition_created",
            ],
            postconditions=[
                "numeric_isotropic_electromagnetic_properties_only",
                "material_name_absent_from_project_and_aedt_libraries",
                "full_project_material_catalog_snapshot_unchanged_before_apply",
                "typed_property_and_optional_appearance_readback_verified",
                "new_material_removed_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.material.assign",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_material_assign",
                "apply_live_hfss_material_assign",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_object_material_and_solve_inside_changed",
                "object_appearance_may_follow_material",
            ],
            postconditions=[
                "exact_solid_object_names_only",
                "existing_project_material_only",
                "target_and_material_snapshot_unchanged",
                "material_and_solve_inside_readback_verified",
                "batch_rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.mesh.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_mesh_inventory"],
            postconditions=[
                "design_unchanged",
                "bounded_mesh_operation_inventory_returned",
                "mesh_property_digests_returned",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.mesh.length.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_length_mesh_create",
                "apply_live_hfss_length_mesh_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_length_mesh_operation_created",
            ],
            postconditions=[
                "exact_solid_object_names_only",
                "bounded_length_and_element_constraints",
                "target_and_mesh_snapshot_unchanged",
                "length_mesh_readback_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.far_field.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_far_field_inventory"],
            postconditions=[
                "design_unchanged",
                "bounded_field_setup_inventory_returned",
                "radiated_field_prerequisites_reported",
                "field_setup_property_digests_returned",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.far_field.infinite_sphere.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_infinite_sphere_create",
                "apply_live_hfss_infinite_sphere_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_infinite_sphere_field_setup_created",
            ],
            postconditions=[
                "radiation_pml_or_hybrid_boundary_required",
                "solution_type_supports_radiated_fields",
                "bounded_angle_sample_count",
                "field_setup_and_boundary_snapshot_unchanged",
                "infinite_sphere_readback_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.surface_boundary.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_surface_boundary_inventory"],
            postconditions=[
                "design_unchanged",
                "bounded_boundary_inventory_returned",
                "explicit_assignments_and_typed_options_returned",
                "boundary_property_digests_returned",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.surface_boundary.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_surface_boundary_create",
                "apply_live_hfss_surface_boundary_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_surface_boundary_created",
            ],
            postconditions=[
                "perfect_e_h_finite_conductivity_impedance_or_lumped_rlc_only",
                "explicit_object_names_or_face_ids_only",
                "impedance_requires_sheet_objects",
                "lumped_rlc_requires_one_planar_sheet_and_bounded_passive_values",
                "infinite_ground_requires_planar_sheet_or_face",
                "finite_conductivity_requires_existing_material",
                "target_geometry_boundary_and_material_snapshot_unchanged",
                "typed_boundary_readback_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.coordinate_system.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_coordinate_system_inventory"],
            postconditions=[
                "design_unchanged",
                "bounded_coordinate_system_inventory_returned",
                "active_working_coordinate_system_returned",
                "typed_property_digests_returned",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.coordinate_system.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_coordinate_system_create",
                "apply_live_hfss_coordinate_system_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_relative_coordinate_system_created",
            ],
            postconditions=[
                "relative_axis_position_coordinate_system_only",
                "global_or_existing_relative_reference_only",
                "finite_noncollinear_axes",
                "coordinate_system_and_variable_snapshot_unchanged",
                "typed_origin_axis_and_reference_readback_verified",
                "prior_active_working_coordinate_system_restored",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.geometry.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_geometry_create",
                "apply_live_hfss_geometry_create",
            ],
            approval="external_host_token",
            side_effects=["project_becomes_dirty", "hfss_objects_created"],
            postconditions=[
                "typed_primitives_only",
                "geometry_snapshot_unchanged",
                "object_count_bounded",
                "batch_readback_verified",
                "batch_rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.geometry_boundary.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_geometry_boundary_create",
                "apply_live_hfss_geometry_boundary_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_objects_created",
                "hfss_boundaries_created",
            ],
            postconditions=[
                "typed_primitives_and_face_selectors_only",
                "geometry_and_boundary_snapshot_unchanged",
                "object_and_boundary_counts_bounded",
                "geometry_and_boundary_readback_verified",
                "atomic_rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.setup.create",
            "reversible_edit",
            ["live"],
            ["preview_live_hfss_setup_create", "apply_live_hfss_setup_create"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=["setup_readback_verified", "rollback_on_failure", "project_not_saved"],
        ),
        _cap(
            "hfss.setup.update",
            "reversible_edit",
            ["live"],
            ["preview_live_hfss_setup_update", "apply_live_hfss_setup_update"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=["setup_snapshot_unchanged", "readback_verified", "rollback_on_failure"],
        ),
        _cap(
            "aedt.frequency_sweep.create",
            "reversible_edit",
            ["live"],
            ["preview_live_frequency_sweep_create", "apply_live_frequency_sweep_create"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=["bounded_range", "setup_snapshot_unchanged", "readback_verified", "rollback_on_failure"],
        ),
        _cap(
            "hfss.setup_sweep.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_hfss_setup_sweep_create",
                "apply_live_hfss_setup_sweep_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "hfss_setup_created",
                "hfss_frequency_sweep_created",
            ],
            postconditions=[
                "typed_setup_properties_only",
                "bounded_sweep_range_and_point_count",
                "setup_snapshot_unchanged",
                "setup_and_sweep_readback_verified",
                "atomic_rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.report.create",
            "reversible_edit",
            ["live"],
            ["preview_live_hfss_report_create", "apply_live_hfss_report_create"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=["report_readback_verified", "rollback_on_failure", "project_not_saved"],
        ),
        _cap(
            "hfss.port.inventory",
            "read_only",
            ["live"],
            ["get_live_hfss_port_inventory"],
            postconditions=[
                "wave_and_lumped_port_assignments_read",
                "typed_port_properties_read",
                "design_unchanged",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.boundary.create",
            "reversible_edit",
            ["live"],
            ["preview_live_hfss_boundary_create", "apply_live_hfss_boundary_create"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=[
                "radiation_uses_explicit_face_ids",
                "wave_port_uses_one_planar_face",
                "lumped_port_uses_one_planar_sheet",
                "driven_modal_typed_port_contract",
                "integration_line_resolved_before_approval",
                "geometry_digest_unchanged",
                "typed_boundary_or_port_readback_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["hfss"],
        ),
        _cap(
            "hfss.analysis.start",
            "expensive",
            ["live"],
            ["preview_live_hfss_analysis_start", "apply_live_hfss_analysis_start"],
            approval="external_host_token",
            side_effects=["solver_job_started"],
            postconditions=["setup_digest_unchanged", "resource_budget_bounded", "non_blocking"],
            products=["hfss", "layout"],
        ),
        _cap(
            "hfss.analysis.status",
            "read_only",
            ["live"],
            ["get_live_hfss_analysis_status"],
            products=["hfss", "layout"],
        ),
        _cap(
            "hfss.analysis.cancel",
            "expensive",
            ["live"],
            ["preview_live_hfss_analysis_cancel", "apply_live_hfss_analysis_cancel"],
            approval="external_host_token",
            side_effects=["running_solver_job_interrupted"],
            postconditions=["running_state_digest_unchanged_before_cancel"],
            products=["hfss", "layout"],
        ),
        _cap(
            "hfss.results.export",
            "persistent_write",
            ["live"],
            ["preview_live_hfss_results_export", "apply_live_hfss_results_export"],
            approval="external_host_token",
            side_effects=["result_artifacts_written_to_managed_export_root"],
            postconditions=["design_unchanged", "artifact_sha256_verified", "evidence_manifest_written"],
            products=["hfss", "layout"],
        ),
        _cap(
            "layout.paths.list",
            "read_only",
            ["artifact", "live"],
            ["list_layout_paths", "list_live_layout_paths"],
            postconditions=["design_unchanged"],
        ),
        _cap(
            "layout.routing.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_routing_inventory"],
            postconditions=["design_unchanged", "variables_and_routing_dimensions_returned"],
        ),
        _cap(
            "layout.technology.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_technology_inventory"],
            postconditions=[
                "design_unchanged",
                "stackup_and_padstack_records_bounded",
                "aedt_port_order_returned",
                "differential_pair_terminal_mapping_returned_when_available",
                "temporary_diff_pair_file_removed",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.material.create_and_assign",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_material_create_assign",
                "apply_live_layout_material_create_assign",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "new_project_material_definition_created",
                "one_stackup_layer_material_field_changed",
            ],
            postconditions=[
                "numeric_isotropic_electromagnetic_properties_only",
                "exact_existing_signal_or_dielectric_layer_only",
                "material_name_absent_from_project_and_aedt_libraries",
                "full_material_catalog_and_stackup_snapshot_unchanged_before_apply",
                "material_class_matches_stackup_layer_role",
                "typed_material_and_exact_layer_field_readback_verified",
                "layer_restored_before_new_material_removal_on_failure",
                "project_not_saved",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.vias.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_via_create",
                "apply_live_layout_via_create",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "new_layout_vias_created",
            ],
            postconditions=[
                "one_to_32_exact_via_names_only",
                "existing_padstack_signal_layers_and_net_only",
                "numeric_coordinates_rotation_and_optional_hole_override_only",
                "dependency_snapshot_unchanged_before_apply",
                "native_via_property_readback_verified",
                "batch_rollback_on_failure",
                "project_not_saved",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.vias.update",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_via_update",
                "apply_live_layout_via_update",
            ],
            approval="external_host_token",
            side_effects=[
                "project_becomes_dirty",
                "existing_layout_vias_changed",
            ],
            postconditions=[
                "one_to_32_exact_existing_vias_only",
                "existing_exact_net_names_only",
                "numeric_model_unit_location_and_rotation_only",
                "full_stackup_net_catalog_and_native_target_snapshot_unchanged_before_apply",
                "only_requested_native_via_properties_changed",
                "full_native_target_snapshot_rollback_on_failure",
                "project_not_saved",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.connectivity.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_connectivity_inventory"],
            postconditions=[
                "design_unchanged",
                "exact_net_and_component_selectors_verified",
                "net_component_pin_via_relations_returned",
                "each_flat_record_section_bounded",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.port_candidates.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_port_candidate_inventory"],
            postconditions=[
                "design_unchanged",
                "exact_signal_and_reference_nets_verified",
                "legacy_component_candidate_scoring_reused",
                "candidate_output_bounded",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.component_ports.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_component_ports_create",
                "apply_live_layout_component_ports_create",
            ],
            approval="external_host_token",
            side_effects=["project_becomes_dirty", "layout_ports_created"],
            postconditions=[
                "component_and_net_snapshot_unchanged",
                "new_port_count_bounded_and_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.edge_port_candidates.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_edge_port_candidate_inventory"],
            postconditions=[
                "design_unchanged",
                "exact_signal_nets_layer_and_bbox_side_verified",
                "legacy_uniform_line_candidate_algorithm_reused",
                "coordinates_normalized_to_bbox_unit",
                "candidate_output_bounded",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.edge_ports.create",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_edge_ports_create",
                "apply_live_layout_edge_ports_create",
            ],
            approval="external_host_token",
            side_effects=["project_becomes_dirty", "layout_edge_ports_created"],
            postconditions=[
                "explicit_primitive_and_edge_snapshot_unchanged",
                "circuit_wave_and_optional_reference_options_typed",
                "one_new_port_per_target_verified",
                "rollback_on_failure",
                "project_not_saved",
            ],
            products=["layout"],
        ),
        _cap(
            "layout.objects.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_object_inventory"],
            postconditions=["design_unchanged", "layout_object_categories_returned"],
        ),
        _cap(
            "layout.object_properties.inventory",
            "read_only",
            ["live"],
            ["get_live_layout_object_property_inventory"],
            postconditions=["design_unchanged", "explicit_via_or_component_properties_returned"],
        ),
        _cap(
            "layout.object_properties.update",
            "reversible_edit",
            ["live"],
            [
                "preview_live_layout_object_property_update",
                "apply_live_layout_object_property_update",
            ],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=["snapshot_unchanged", "readback_verified", "batch_rollback_on_failure"],
        ),
        _cap(
            "aedt.variables.inventory",
            "read_only",
            ["live"],
            ["get_live_aedt_variable_inventory"],
            postconditions=["design_unchanged", "project_and_design_variables_returned"],
        ),
        _cap(
            "aedt.variables.upsert",
            "reversible_edit",
            ["live"],
            ["preview_live_aedt_variable_upsert", "apply_live_aedt_variable_upsert"],
            approval="external_host_token",
            side_effects=["project_becomes_dirty"],
            postconditions=[
                "full_variable_expression_snapshot_unchanged",
                "existing_variable_metadata_preserved",
                "readback_verified",
                "rollback_verified",
                "project_not_saved",
            ],
        ),
        _cap(
            "aedt.variables.batch_upsert",
            "reversible_edit",
            ["live"],
            [
                "preview_live_aedt_variable_batch_upsert",
                "apply_live_aedt_variable_batch_upsert",
            ],
            approval="external_host_token",
            side_effects=["project_becomes_dirty", "aedt_variables_created_or_updated"],
            postconditions=[
                "one_to_32_ordered_variables",
                "hfss_or_hfss_3d_layout_only",
                "case_insensitive_names_unique",
                "full_variable_expression_snapshot_unchanged",
                "existing_variable_metadata_preserved",
                "per_variable_readback_verified",
                "atomic_rollback_verified",
                "project_not_saved",
            ],
        ),
        _cap(
            "layout.path_width.parameterize",
            "reversible_edit",
            ["artifact", "live"],
            [
                "preview_parameterize_path_width",
                "apply_parameterize_path_width",
                "preview_live_parameterize_path_width",
                "apply_live_parameterize_path_width",
            ],
            approval="external_host_token_for_live",
            postconditions=["target_digest_unchanged", "readback_verified", "rollback_on_failure"],
        ),
        _cap(
            "exploration.operation.propose_validate",
            "read_only",
            ["live"],
            ["get_ansys_operation_plan_schema", "propose_ansys_operation", "validate_ansys_operation"],
            postconditions=["declarative_plan_only", "current_version_source_evidence", "policy_validated"],
        ),
        _cap(
            "exploration.operation.execute",
            "reversible_edit",
            ["live"],
            ["preview_exploratory_operation", "apply_exploratory_operation"],
            approval="external_host_token_for_reversible_edit",
            side_effects=["bounded_live_property_edit"],
            postconditions=["target_digest_unchanged", "readback_verified", "server_snapshot_rollback"],
        ),
        _cap(
            "capability.trace.capture",
            "read_only",
            ["live"],
            ["capture_capability_trace"],
            postconditions=["server_owned_trace_only", "append_only_event_log", "secrets_redacted"],
        ),
        _cap(
            "capability.promotion.generate",
            "read_only",
            ["live"],
            ["promote_ansys_capability"],
            side_effects=["writes_disabled_candidate_under_managed_review_root"],
            postconditions=["verified_trace_only", "no_auto_apply", "no_hot_registration", "no_commit"],
        ),
        _cap(
            "workflow.graph.catalog",
            "read_only",
            ["workflow"],
            ["list_ansys_workflows", "inspect_ansys_workflow", "get_ansys_workflow_status"],
            postconditions=["allowlisted_templates_only", "graph_state_unchanged"],
        ),
        _cap(
            "workflow.graph.execute",
            "expensive",
            ["workflow"],
            [
                "preview_ansys_workflow_start",
                "apply_ansys_workflow_start",
                "preview_ansys_workflow_advance",
                "apply_ansys_workflow_advance",
            ],
            approval="external_host_token_per_start_and_step",
            side_effects=["mission_state_written", "approved_graph_step_may_run_workers"],
            postconditions=["target_binding_verified", "one_scheduler_step_per_apply"],
        ),
        _cap(
            "layout.results.touchstone_score",
            "persistent_write",
            ["workflow"],
            [
                "inspect_ansys_workflow",
                "preview_ansys_workflow_start",
                "apply_ansys_workflow_start",
                "preview_ansys_workflow_advance",
                "apply_ansys_workflow_advance",
            ],
            approval="external_host_token_per_step_and_export",
            side_effects=["touchstone_and_score_evidence_written_to_managed_export_root"],
            postconditions=[
                "workflow_ids_layout_live_touchstone_score_and_compositions",
                "explicit_port_order_and_mapping_verified",
                "source_artifact_sha256_verified",
                "project_unchanged_and_not_saved",
            ],
            products=["layout"],
        ),
    ]
    unavailable = []
    if desktop_bound:
        available = []
        for capability in capabilities:
            tools = [tool for tool in capability["tools"] if tool not in _DESKTOP_BOUND_HIDDEN_TOOLS]
            if not tools:
                unavailable.append(
                    {
                        "name": capability["name"],
                        "reason": "unavailable_in_desktop_bound_scope",
                    }
                )
                continue
            filtered = dict(capability)
            filtered["tools"] = tools
            filtered["modes"] = [mode for mode in capability["modes"] if mode != "artifact"]
            available.append(filtered)
        capabilities = available
    return {
        "version": "2",
        "scope": "desktop_bound" if desktop_bound else "unified",
        "compatibility": {
            "v1_unchanged": True,
            "workflow_graph_unchanged": True,
            "workflow_mcp_added": True,
        },
        "defaults": {
            "implicit_live_target": False,
            "release_required": True,
            "live_apply_saves_project": False,
            "code_fallback_enabled": False,
        },
        "capabilities": capabilities,
        "unavailable_capabilities": unavailable,
    }


def _cap(
    name: str,
    risk: str,
    modes: list[str],
    tools: list[str],
    *,
    approval: str = "none",
    side_effects: list[str] | None = None,
    postconditions: list[str] | None = None,
    products: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "risk": risk,
        "modes": modes,
        "tools": tools,
        "approval": approval,
        "side_effects": side_effects or [],
        "postconditions": postconditions or [],
        "products": products or [],
    }
